perple-personality-plan-project/backend

- migrations/20230107013518-Feed.js
- migrations/20230107015754-Comment.js
- migrations/20230107020128-Like.js
- src/db/models/comment.models.ts
- src/db/models/feed.models.ts
- src/db/models/like.models.ts
Feed, Comment, Like 테이블 및 모델 생성
확인 부탁드립니다:)
> Feed, Comment, Like 테이블 및 모델 생성

- migrations/20230107020802-Follwer.js
- migrations/20230107021351-GroupUser.js
- src/db/models/follower.models.ts
- src/db/models/groupUser.models.ts
<FEAT> GroupUser, Follower 테이블 및 모델 생성
> <FEAT> GroupUser, Follower 테이블 및 모델 생성

- migrations/20230107015405-Group.js
- migrations/20230107020052-hashtag.js
- migrations/20230107030053-GroupHahtag.js
- src/db/models/group.models.ts
- src/db/models/groupHahtag.models.ts
- src/db/models/hashtag.models.ts
- src/db/models/user.models.ts
Group, GroupHashtag, HashTag 테이블 및 모델 생성
> <FEAT> : Group, GroupHashtag, HashTag 테이블 및 모델 생성

- src/db/models/comment.models.ts
- src/db/models/feed.models.ts
- src/db/models/follower.models.ts
- src/db/models/group.models.ts
- src/db/models/groupHahtag.models.ts
- src/db/models/groupUser.models.ts
- src/db/models/hashtag.models.ts
- src/db/models/like.models.ts
- src/db/models/user.models.ts
모든 ERD에 맞게 모델파일에 설정 적용
- PrimaryKey -> AutoIncrement
- AllowNull -> false
- Unique
> <FIX> : ORM 모델 관계 설정 및 ERD 적용

- package-lock.json
- package.json
- src/api/user/controller/user.controller.ts
- src/api/user/dto/create-user.dto.ts
- src/api/user/service/user.service.ts
- src/api/user/user.module.ts
- src/api/user/user.repository.ts
class-validator 사용 Body 유효성 검사
로그인 아이디, 닉네임 중복 검사 구현
> <FEAT> 회원가입 기능구현

- migrations/2022011202-maps.js
> <STYLE> : 변수명 오탈자 수정

- src/api/feed/controller/feed.controller.ts
- src/api/feed/feed.module.ts
- src/api/feed/feed.repository.ts
- src/api/feed/service/feed.service.ts
- src/api/group/controller/group.controller.ts
- src/api/group/dto/group.request.dto.ts
- src/api/group/group.module.ts
- src/api/user/user.module.ts
- src/auth/local/local.strategy.ts
> <FIX> : DB 모듈적용

- migrations/2022011207-group_users.js
- src/api/group/controller/group.controller.ts
- src/api/group/group.repository.ts
- src/api/group/service/group.service.ts
- src/db/models/group.models.ts
- src/db/models/groupUser.models.ts
- src/db/models/hashtag.models.ts
1. 해시태그 기능 추가
2. 그룹 유저테이블에 추가
3. group_users => createdAt,updatedAt 수정
4. group.models파일 groupUser 추가
> <FIX> : 그룹 생성 API 구현

- migrations/2022011207-group_users.js
- src/api/group/controller/group.controller.ts
- src/api/group/group.repository.ts
- src/api/group/service/group.service.ts
- src/db/models/group.models.ts
- src/db/models/groupUser.models.ts
- src/db/models/hashtag.models.ts
> <FEAT> : 그룹 가입 API 구현

- src/api/user/controller/user.controller.ts
- src/api/user/user.repository.ts
- src/auth/auth.service.ts
- src/auth/jwt/jwt-refresh.strategy.ts
- src/auth/jwt/jwt.strategy.ts
- src/auth/local/local.strategy.ts
db컬럼과 변수명 맞춤 
페이로드에 login_id -> user_id
> <FIX>: 로그인 api 수정

- src/api/feed/controller/feed.controller.ts
- src/api/feed/dto/feed.request.dto.ts
- src/api/feed/feed.repository.ts
- src/api/feed/service/feed.service.ts
> <Feat> : 피드 상세조회 api 완성

- src/api/feed/controller/feed.controller.ts
- src/api/feed/dto/feed.request.dto.ts
- src/api/feed/feed.repository.ts
- src/api/feed/service/feed.service.ts
> <FEAT> : 피드 전체조회 api (mbti별 미완성)

- src/api/feed/controller/feed.controller.ts
- src/api/feed/dto/feed.request.dto.ts
- src/api/feed/feed.repository.ts
- src/api/feed/service/feed.service.ts
> <FEAT> : 피드 삭제하기(유저인증 제외)

- src/api/group/controller/group.controller.ts
- src/api/group/group.module.ts
- src/api/group/group.repository.ts
- src/api/group/service/group.service.ts
- src/common/pipes/positiveInt.pipe.ts
> <FEAT> : 그룹 게시물 작성 api 구현

- src/api/user/controller/user.controller.ts
- src/api/user/service/user.service.ts
- src/api/user/user.repository.ts
- src/auth/jwt/jwt-refresh.strategy.ts
컨플릭 수정 후 오류 나는 부분 수정 
modified:   src/auth/jwt/jwt-refresh.strategy.ts
> <FIX>: 컨플릭 오류 수정

- package-lock.json
- package.json
modified:   package-lock.json
modified:   package.json
> <CHORE>: passport-kakao 추가

- src/api/user/controller/user.controller.ts
프론트 작동 시험을 위해 제거
user_id 는 1로 고정
> <FIX>: 마이페이지 조회, 프로필 수정 auth guard 제거

- src/api/comment/comment.module.ts
- src/api/comment/comment.repository.ts
- src/api/comment/controller/comment.controller.spec.ts
- src/api/comment/controller/comment.controller.ts
- src/api/comment/dto/comment.request.dto.ts
- src/api/comment/service/comment.service.spec.ts
- src/api/comment/service/comment.service.ts
- src/api/feed/feed.repository.ts
- src/api/feed/service/feed.service.ts
- src/app.module.ts
- src/db/models/comment.models.ts
feed 상세 조회에서 like_count 임시 제외된 상태
#14
> <FEAT> : 코멘트 생성 api 완성 / 코멘트 db model 수정 / 피드 상세조회 댓글 추가

- src/api/comment/comment.module.ts
- src/api/comment/comment.repository.ts
- src/api/comment/controller/comment.controller.spec.ts
- src/api/comment/controller/comment.controller.ts
- src/api/comment/dto/comment.request.dto.ts
- src/api/comment/service/comment.service.spec.ts
- src/api/comment/service/comment.service.ts
- src/api/feed/feed.repository.ts
- src/api/feed/service/feed.service.ts
- src/app.module.ts
- src/db/models/comment.models.ts
> <FEAT> : 댓글 삭제 api 완성

- package.json
- src/api/group/controller/group.controller.ts
- src/api/group/dto/group.request.dto.ts
- src/api/group/group.module.ts
- src/api/group/group.repository.ts
- src/api/group/service/group.service.ts
- src/common/utils/asw.s3.service.ts
> <FEAT> : 이미지 업로드 구현

- src/api/user/controller/user.controller.ts
- src/api/user/dto/create-user.dto.ts
- src/api/user/service/user.service.ts
- src/api/user/user.repository.ts
- src/auth/auth.service.ts
- src/auth/jwt/jwt-refresh.strategy.ts
- src/auth/jwt/jwt.strategy.ts
- src/auth/kakao/kakao.strategy.ts
프론트에서 header를 받지 못해서 
Body로 변경
> <FIX>: 토큰 전달 Body로 변경

- package-lock.json
- src/api/feed/controller/feed.controller.ts
- src/api/feed/feed.repository.ts
- src/api/feed/service/feed.service.ts
> <FEAT> : 피드 좋아요 api 완성 및 피드 상세조회 닉네임 표기 수정 완료

- src/api/user/service/user.service.ts
- src/api/user/user.repository.ts
회원가입이 안되도 성공메세지를 응답 -> 예외처리 추가
매개변수 수정 객체분해를 안해 insert가 안되는 문제
> <FIX>: 회원가입 로직 수정

- src/api/user/controller/user.controller.ts
- src/api/user/service/user.service.ts
- src/auth/jwt/jwt-auth.guard.ts
- src/auth/jwt/jwt-refresh.strategy.ts
> <FIX> console.log 추가

- src/api/group/group.repository.ts
- src/api/user/controller/user.controller.ts
- src/api/user/service/user.service.ts
- src/api/user/user.module.ts
> <FEAT> : 마이페이지 그룹 모아보기 api 추가

- src/api/user/controller/user.controller.ts
- src/auth/auth.service.ts
- src/auth/jwt/jwt-refresh.strategy.ts
> <FIX>: jwt-refresh.strategy 코드 원상복구

- src/api/feed/controller/feed.controller.ts
- src/api/feed/feed.module.ts
- src/api/feed/feed.repository.ts
- src/api/feed/service/feed.service.ts
> <FIX> : 피드 생성 이미지 업로드 추가 및 게시글 상세 조회 좋아요 수 추가

- migrations/2022011202-maps.js
- src/api/group/controller/group.controller.ts
- src/api/map/controller/map.controller.spec.ts
- src/api/map/controller/map.controller.ts
- src/api/map/map.module.ts
- src/api/map/map.repository.ts
- src/api/map/service/map.service.spec.ts
- src/api/map/service/map.service.ts
- src/app.module.ts
- src/db/models/map.models.ts
1. 맵 저장
2. 맵 리스트
3. 맵 개별 리스트 api 구현
> <FEAT> : MAP API 구현

- src/api/feed/controller/feed.controller.ts
- src/api/feed/dto/feed.request.dto.ts
- src/api/feed/feed.repository.ts
- src/api/feed/service/feed.service.ts
> <FEAT> : mbti별 피드 조회 api완성

- src/api/user/controller/user.controller.ts
- src/api/user/dto/create-user.dto.ts
> <FIX>: 닉네임 정규식 수정

- src/api/user/controller/user.controller.ts
- src/db/models/user.models.ts
> <FIX>: 마이피드 조회 api 주소 변경, 유저 모델 함수 추가

- src/api/group.comment/controller/group.comment.controller.ts
- src/api/group.comment/service/group.comment.service.ts
> <FIX> : 댓글 생성이 안되는 문제 해결

- src/api/group.comment/service/group.comment.service.ts
> <FIX> : 그룹 댓글 삭제 수정

- src/api/group/group.repository.ts
> <FIX> : 그룹 피드 상세조회 api 수정

- src/api/user/controller/user.controller.ts
- src/api/user/service/user.service.ts
- src/api/user/user.repository.ts
- src/auth/auth.service.ts
modified:   src/auth/auth.service.ts
> <FIX>: 로그인시 mbti 리턴 추가, console.log 제거

- src/common/utils/winston.utills.ts
dist -> src
modified:   src/common/utils/winston.utills.ts
> <FIX>: 로그폴더 위치 변경

- src/api/user/controller/user.controller.ts
> <FIX>: 카카오 콜백 api 삭제

- migrations/2022011201-users.js
- src/api/user/controller/user.controller.ts
- src/api/user/service/user.service.ts
- src/api/user/user.module.ts
- src/api/user/user.repository.ts
- src/db/models/user.models.ts
> <FEAT>: 마이페이지 이미지 업데이트 기능구현

- src/common/utils/winston.utills.ts
가독성이 안좋아 format 옵션 추가
modified:   src/common/utils/winston.utills.ts
> <FIX>: 로그 파일 수정

- src/api/group/controller/group.controller.ts
- src/api/group/group.repository.ts
- src/api/group/service/group.service.ts
> <FEAT> : 그룹 삭제 API 구현

- src/api/group/service/group.service.ts
> <Fix> : 그룹 만들기 api 디폴트 이미지가 출력 안되는 문제 수정

- src/api/group/group.repository.ts
> <Fix> : 그룹 삭제 조건 추가

- src/api/comment/controller/comment.controller.ts
- src/api/comment/dto/comment.request.dto.ts
- src/api/feed/controller/feed.controller.ts
- src/api/feed/dto/feed.request.dto.ts
- src/api/user/user.repository.ts
> <FIX> : 마이 피드 location 추가

- src/api/comment/controller/comment.controller.ts
- src/api/comment/dto/comment.request.dto.ts
- src/api/feed/controller/feed.controller.ts
- src/api/feed/dto/feed.request.dto.ts
> <FIX> : 피드, 코멘트 스웨거 제거

- src/api/feed/controller/feed.controller.ts
- src/api/feed/feed.repository.ts
- src/api/feed/service/feed.service.ts
- src/db/models/feed.models.ts
피드 전체 조회, mbti별 조회, 상세 조회
isPick, isLike 추가
> <FIX>: 피드 조회 리턴값 추가

- src/api/comment/comment.repository.ts
- src/api/group.comment/controller/group.comment.controller.ts
- src/api/group.comment/service/group.comment.service.ts
- src/api/group/controller/group.controller.ts
- src/api/group/group.repository.ts
- src/api/group/service/group.service.ts
> <Fix> : 전체 게시글 api 수정

- src/api/user/controller/user.controller.ts
- src/auth/kakao/kakao.strategy.ts
modified:   src/auth/kakao/kakao.strategy.ts
> <FIX>: 카카오 로그인 리턴값에 user_id 추가

- src/api/feed/controller/feed.controller.ts
- src/api/feed/feed.repository.ts
- src/api/feed/service/feed.service.ts
modified:   src/api/feed/controller/feed.controller.ts
modified:   src/api/feed/feed.repository.ts
modified:   src/api/feed/service/feed.service.ts
> <FIX>: 피드 컨트롤러 쿼리 스트링 파이프 제거

- src/api/feed/controller/feed.controller.ts
- src/api/feed/feed.module.ts
- src/api/feed/feed.repository.ts
- src/api/feed/service/feed.service.ts
- src/api/user/controller/user.controller.ts
- src/api/user/service/user.service.ts
- src/api/user/user.repository.ts
user 폴더 --> feed 폴더
modified:   src/api/feed/controller/feed.controller.ts
modified:   src/api/feed/feed.module.ts
modified:   src/api/feed/feed.repository.ts
modified:   src/api/feed/service/feed.service.ts
> <RENAME>: 찜하기 api feed 폴더로 이동

- src/api/group/controller/group.controller.ts
> <Fix> : 그룹 전체 게시글 api의 isLike 수정

- src/api/feed/feed.repository.ts
- src/api/group/controller/group.controller.ts
- src/api/group/group.module.ts
- src/api/group/service/group.service.ts
> <FEAT> : 그룹 게시글 삭제 api 구현

- src/api/feed/feed.repository.ts
modified:   src/api/feed/feed.repository.ts
> <FIX>: 게시물 조회 isLike, isPick 수정

- src/api/user/dto/request/create-user.dto.ts
- src/api/user/dto/request/update-user.dto.ts
- src/common/decorators/validateMbti.ts
- src/db/models/user.models.ts
modified:   src/api/user/dto/request/create-user.dto.ts
modified:   src/api/user/dto/request/update-user.dto.ts
new file:   src/common/decorators/validateMbti.ts
modified:   src/db/models/user.models.ts
> <FEAT>: mbti 유효성 검사 데코레이터 추가

- src/api/user/user.repository.ts
- src/common/decorators/validateMbti.ts
modified:   src/common/decorators/validateMbti.ts
> <FIX>: 마이 피드. 마이 픽 조회시 isLike, isPick 추가

- src/api/user/user.repository.ts
Feed.feed_id --> feed.feed_id
테이블 명으로 바꾸어 줌
> <FIX>: my-pick 조회시 500에러 수정

- src/api/user/service/user.service.ts
- src/db/models/user.models.ts
마이페이지 이미지 업데이트 시 기존 이지미 삭제
modified:   src/db/models/user.models.ts
> <FIX>: 마이페이지 이미지 업데이트 수정

- src/api/feed/feed.repository.ts
> <FIX> : 피드 댓글 최신순 정렬

- src/api/feed/feed.repository.ts
> <FIX> : 댓글 프로필 이미지 추가

- src/api/feed/feed.repository.ts
> <FIX> : 댓글 프로필 이미지 추가 수정

- src/api/feed/feed.repository.ts
> <FIX> : 여러 피드 조회들 프로필 이미지 추가

- src/api/user/controller/user.controller.ts
- src/api/user/dto/request/update-user.dto.ts
- src/api/user/service/user.service.ts
- src/api/user/user.repository.ts
- src/auth/kakao/kakao.strategy.ts
- src/common/decorators/validateMbti.ts
modified:   src/api/user/dto/request/update-user.dto.ts
modified:   src/auth/kakao/kakao.strategy.ts
modified:   src/common/decorators/validateMbti.ts
> <FEAT>: 소셜 로그인 유저 mbti update api 기능구현

- src/api/user/controller/user.controller.ts
- src/api/user/dto/request/create-user.dto.ts
- src/api/user/service/user.service.ts
- src/api/user/user.repository.ts
- src/auth/jwt/jwt.strategy.ts
유저 피드백 반영
modified:   src/api/user/dto/request/create-user.dto.ts
modified:   src/auth/jwt/jwt.strategy.ts
> <FIX>: 로그인아이디. 닉네임 중복검사 로직 분리

- src/api/feed/feed.repository.ts
> <FIX> : 닉네임 누락 수정

- src/api/user/service/user.service.ts
- src/auth/kakao/kakao.strategy.ts
modified:   src/auth/kakao/kakao.strategy.ts
> <FIX>: 카카오 로그인시 닉네임 실명으로 변경

- package.json
> <CHORE>: jest 설정 변경

- src/api/feed/controller/feed.controller.ts
- src/api/feed/feed.repository.ts
- src/api/feed/service/feed.service.ts
> <FIX> : feed pagenation
